server:
  port: 8081
spadas:
  dimension: 2
  resolution: 10
  leaf-capacity: 1000
  cache-dataset: true
  cache-index: true
  save-index: true
  frontend-limitation: 10000
  file:
    baseUri: ./dataset/
    staticUri: /dataset/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus, health, metrics
    health:
      show-details: always
  metrics:
    distribution:
      sla:
        http:
          server:
            requests: 1ms,5ms,10ms,50ms,100ms,200ms,500ms,1s,5s
    tags:
      application: Spadas
